feat: Add middleware and refactoring
lucaspineda/recipe-app-server pull request #1
Opened 2024-08-26 19:36 UTC by Jefferson-W

2024-08-26 20:24 UTC, lucaspineda requested changes

2024-08-26 20:24 UTC, lucaspineda commented on src/middleware/verifyToken.ts
> +    }
Não precisa desse if aqui, se o token for null vai cair no catch() do verifyIdToken() e já vai retornar o erro.

`const idToken = req.headers.authorization` é o suficiente

2024-08-26 20:24 UTC, lucaspineda commented on src/middleware/verifyToken.ts
> +        const uid = decodedToken.uid;
Futuramente vamos precisar desse uid pra gravar na tabela de usuários. Pra isso precisa passar o uid para o controller. Pode fazer isso?
Creio que a melhor forma é fazendo algo do tipo `req.uid = uid`. E depois você consegue acessar o uid no controller.

2024-08-26 20:24 UTC, lucaspineda commented on src/middleware/verifyToken.ts
> +        // return res.status(403).json({ error: error })
Deletar essa linha

2024-08-26 20:24 UTC, lucaspineda commented on src/routes/index.ts
> +  app.use('/teste', teste)
Aqui seria um .get não .use

2024-08-27 12:22 UTC, Jefferson-W commented
Pontos ajustados

2024-08-27 12:59 UTC, lucaspineda commented on src/app.ts
É melhor usar o middleware neste arquivo com app.use() já que ele vai ser utilizado em todas as rotas, não só em rotas específicas

2024-08-27 17:21 UTC, lucaspineda approved these changes

2024-08-27 17:22 UTC, merged